In [2]:
import pandas as pd

In [3]:
pd.read_json("./test.json")

,ltp,vol_traded_today,last_traded_time,exch_feed_time,bid_size,ask_size,bid_price,ask_price,last_traded_qty,tot_buy_qty,...,low_price,high_price,lower_ckt,upper_ckt,open_price,prev_close_price,type,symbol,ch,chp
0,161.00,121088950.0,2025-01-29 09:59:59,2025-01-29 11:13:05,250.0,225.0,160.05,161.10,25.0,229175.0,...,67.65,180.70,0.0,0.0,67.65,64.70,sf,NSE:NIFTY25JAN23150CE,96.30,148.8408
1,118.40,142465350.0,2025-01-29 09:59:59,2025-01-29 11:13:05,375.0,250.0,118.30,119.45,25.0,116275.0,...,116.95,234.95,0.0,0.0,172.50,208.95,sf,NSE:NIFTY25JAN23100PE,-90.55,-43.3357
2,190.65,185020775.0,2025-01-29 09:59:59,2025-01-29 11:13:05,300.0,225.0,190.90,192.00,25.0,309400.0,...,86.45,210.00,0.0,0.0,86.45,82.35,sf,NSE:NIFTY25JAN23100CE,108.30,131.5118
3,133.80,163764750.0,2025-01-29 09:59:59,2025-01-29 11:13:06,350.0,225.0,132.90,133.80,125.0,317525.0,...,53.25,153.00,0.0,0.0,57.00,50.40,sf,NSE:NIFTY25JAN23200CE,83.40,165.4762
4,137.40,68513225.0,2025-01-29 09:59:59,2025-01-29 11:13:06,1000.0,125.0,137.40,138.65,25.0,65050.0,...,137.15,268.50,0.0,0.0,203.25,239.15,sf,NSE:NIFTY25JAN23150PE,-101.75,-42.5465
5,283.80,20558985.0,2025-01-29 09:59:59,2025-01-29 11:12:46,15.0,105.0,281.95,283.90,120.0,46770.0,...,208.70,352.85,0.0,0.0,234.90,186.25,sf,NSE:BANKNIFTY25JAN49200CE,97.55,52.3758
6,367.35,9775485.0,2025-01-29 09:59:59,2025-01-29 11:12:46,15.0,90.0,364.35,367.35,15.0,18795.0,...,358.25,612.70,0.0,0.0,498.95,560.00,sf,NSE:BANKNIFTY25JAN49200PE,-192.65,-34.4018
7,236.80,13264425.0,2025-01-29 09:59:58,2025-01-29 11:12:46,1305.0,120.0,236.75,237.80,60.0,30975.0,...,172.20,308.05,0.0,0.0,186.00,155.50,sf,NSE:BANKNIFTY25JAN49300CE,81.30,52.2830
8,421.90,4201215.0,2025-01-29 09:59:59,2025-01-29 11:12:46,105.0,690.0,416.60,422.90,15.0,18765.0,...,413.95,675.50,0.0,0.0,548.95,632.00,sf,NSE:BANKNIFTY25JAN49300PE,-210.10,-33.2437
9,160.10,51964550.0,2025-01-29 09:59:59,2025-01-29 11:13:07,4175.0,250.0,160.00,160.90,25.0,82575.0,...,160.00,302.50,0.0,0.0,250.00,274.40,sf,NSE:NIFTY25JAN23200PE,-114.30,-41.6545
10,333.10,25868460.0,2025-01-29 09:59:59,2025-01-29 11:12:46,30.0,360.0,333.10,335.00,45.0,32160.0,...,240.05,400.90,0.0,0.0,285.70,221.30,sf,NSE:BANKNIFTY25JAN49100CE,111.80,50.5197
11,23163.10,NaN,NaT,2025-01-29 12:02:20,NaN,NaN,NaN,NaN,NaN,NaN,...,22976.50,23183.35,NaN,NaN,23026.75,22957.25,if,NSE:NIFTY50-INDEX,205.85,0.9000
12,23163.10,NaN,NaT,2025-01-29 12:02:22,NaN,NaN,NaN,NaN,NaN,NaN,...,22976.50,23183.35,NaN,NaN,23026.75,22957.25,if,NSE:NIFTY50-INDEX,205.85,0.9000
13,319.20,16730415.0,2025-01-29 09:59:59,2025-01-29 11:12:46,15.0,570.0,316.10,319.20,30.0,23580.0,...,306.80,546.80,0.0,0.0,474.65,496.45,sf,NSE:BANKNIFTY25JAN49100PE,-177.25,-35.7035
14,49165.95,NaN,NaT,2025-01-29 12:02:20,NaN,NaN,NaN,NaN,NaN,NaN,...,48849.80,49199.65,NaN,NaN,48997.20,48866.85,if,NSE:NIFTYBANK-INDEX,299.10,0.6100
15,49165.95,NaN,NaT,2025-01-29 12:02:22,NaN,NaN,NaN,NaN,NaN,NaN,...,48849.80,49199.65,NaN,NaN,48997.20,48866.85,if,NSE:NIFTYBANK-INDEX,299.10,0.6100